default:
  service:
    name: sr-bob
    host: 0.0.0.0
    port: 3008
    version: v1
    protocol: http
    limitTransfer: 10mb
    databases:
      main:
        dialect: mongodb
        host: mongodb+srv://direction.mongo/test?retryWrites=true&w=majority
        port: 27017
        dbName: test
        user: test
        password: test123
